name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build & Push Image
      run: |
        echo "${{ secrets.imsari}}" | docker login  -u imsari --password-stdin
        docker image build -t imsari/bd24_project_a11_b:tagname .
        docker push imsari/bd24_project_a11_b:tagname
